"""create citations table

Revision ID: 84823fea808c
Revises: 88945cba5ff1
Create Date: 2026-09-29 22:25:24.640256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84823fea808c'
down_revision: Union[str, Sequence[str], None] = '88945cba5ff1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('citations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('citing_case_id', sa.Integer(), nullable=False),
    sa.Column('cited_case_name', sa.String(length=500), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('reporter', sa.String(length=50), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('pin_cite', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['citing_case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citations_citing_case_id'), 'citations', ['citing_case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_citations_citing_case_id'), table_name='citations')
    op.drop_table('citations')
    # ### end Alembic commands ###
