"""add updated count to ingestion jobs

Revision ID: 88945cba5ff1
Revises: 741a46161465
Create Date: 2026-09-29 21:39:47.631223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88945cba5ff1'
down_revision: Union[str, Sequence[str], None] = '741a46161465'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    op.add_column(
        "ingestion_jobs",
        sa.Column(
            "updated_count",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
    )

    op.alter_column(
        "ingestion_jobs",
        "updated_count",
        server_default=None,
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingestion_jobs', 'updated_count')
    # ### end Alembic commands ###
