"""create courts and cases

Revision ID: de80a93060e3
Revises: 
Create Date: 2026-09-28 19:50:37.841309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de80a93060e3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('abbreviation', sa.String(length=50), nullable=False),
    sa.Column('jurisdiction', sa.String(length=100), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abbreviation'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_courts_id'), 'courts', ['id'], unique=False)
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('case_name', sa.String(length=500), nullable=False),
    sa.Column('court_id', sa.Integer(), nullable=False),
    sa.Column('decision_date', sa.Date(), nullable=True),
    sa.Column('docket_number', sa.String(length=100), nullable=True),
    sa.Column('opinion_text', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['court_id'], ['courts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_case_name'), 'cases', ['case_name'], unique=False)
    op.create_index(op.f('ix_cases_content_hash'), 'cases', ['content_hash'], unique=True)
    op.create_index(op.f('ix_cases_court_id'), 'cases', ['court_id'], unique=False)
    op.create_index(op.f('ix_cases_decision_date'), 'cases', ['decision_date'], unique=False)
    op.create_index(op.f('ix_cases_external_id'), 'cases', ['external_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cases_external_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_decision_date'), table_name='cases')
    op.drop_index(op.f('ix_cases_court_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_content_hash'), table_name='cases')
    op.drop_index(op.f('ix_cases_case_name'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_courts_id'), table_name='courts')
    op.drop_table('courts')
    # ### end Alembic commands ###
