  services:
  api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: caseflow_api
    restart: unless-stopped

    environment:
      DATABASE_URL: postgresql+psycopg://caseflow:caseflow@db:5432/caseflow

    ports:
      - "8000:8000"

    depends_on:
      db:
        condition: service_healthy