services:
  db:
    image: postgres:17
    container_name: caseflow-db
    environment:
      POSTGRES_USER: caseflow
      POSTGRES_PASSWORD: caseflow
      POSTGRES_DB: caseflow
    ports:
      - "5432:5432"
    volumes:
      - caseflow-postgres-data:/var/lib/postgresql/data

volumes:
  caseflow-postgres-data: